name: spray-surrogate
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.3
  - pytorch-cuda=12.1
  - numpy
  - h5py
  - scipy
  - pyyaml
  - tensorboard
  - tqdm
  - pip
  - pip:
      - -e ".[dev]"
